[cursor.style]
blinking = "On"
shape = "Block"

[cursor.vi_mode_style]
shape = "Beam"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
option_as_alt = "OnlyLeft"
decorations_theme_variant = "Dark"

[terminal]
osc52 = "CopyPaste"

[general]
import = ["~/.config/alacritty/theme/nord.toml"]
